on:
  push:
    paths:
      - '.github/workflows/with-unknown-values.yml'
      - '.github/workflows/run-with-unknown-values'
name: Linux, with Unknown::Values installed
jobs:
  build_with_unknown_values:
    runs-on: 'ubuntu-latest'
    name: with Unknown::Values installed
    steps:
      - uses: actions/checkout@v6
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.30"
      - name: run tests
        env:
          PERL_USE_UNSAFE_INC: 0
        run: |
            perl -v
            cpanm Unknown::Values
            cpanm ExtUtils::MakeMaker Test::Pod Test::Pod::Coverage
            perl -Mparent -e0
            cpanm --installdeps .
            perl Makefile.PL
            make test TEST_VERBOSE=1
